apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS mydbapp;
    CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '12345678';
    GRANT ALL PRIVILEGES ON mydbapp.* TO 'root'@'%';
    FLUSH PRIVILEGES;
